using System;
using System.Collections.Generic;
using System;
using System.Collections.Generic;
using System.Text;

namespace MemberCrud.Models;
/// <summary>
/// Represents a church member in the Church Member Manager application.
///
/// This class stores personal information, contact details, and membership
/// information for each member. It is used as a data model for SQL Server
/// database operations, Windows Forms user interface display, and business
/// logic throughout the application.
///
/// Member objects are used when adding, editing, deleting, and viewing
/// member records. Required properties help ensure that important
/// information is always provided.
/// </summary>
public class Member
{
    /// <summary>
    /// The unique identifier for the member.
    ///
    /// This value is automatically generated by the database and is
    /// used to identify each member. It is required for database
    /// operations such as updating, deleting, and retrieving records.
    /// </summary>
    public int Id { get; set; }
    /// <summary>
    /// The member's first name.
    ///
    /// This property stores the member's given name and is displayed
    /// throughout the application. It is required to make sure every
    /// member has a recorded first name.
    /// </summary>
    public required string FirstName { get; set; }
    /// <summary>
    /// The member's last name.
    ///
    /// This property stores the member's family name and is used
    /// together with the first name to identify the member.
    /// It is required for all member records.
    /// </summary>

    public required string LastName { get; set; }
    /// <summary>
    /// The member's phone number.
    ///
    /// This property stores the member's primary contact number and
    /// allows the church administration to communicate with the member.
    /// </summary>
    public required string Phone { get; set; }
    /// <summary>
    /// The member's email address.
    ///
    /// This property stores the member's email and is used to send
    /// announcements, newsletters, and other important church
    /// communications.
    /// </summary>
    public required string Email { get; set; }

    public required string MembershipStatus { get; set; }


    public required string Street { get; set; }

    public required string City { get; set; }

    public required string PostalCode { get; set; }

    public DateTime DateOfBirth { get; set; }

    public DateTime CreateAt { get; set; }

}

