using System;
using System.Collections.Generic;
using System.Text;

namespace MemberCrud.Models
{
    /// <summary>
    /// Represents a ministry in the church management system.
    ///
    /// A ministry is a group, department, or area of service in the church.
    /// This class stores the basic information for each ministry.
    ///
    /// Ministry objects can be saved to the database, displayed in the
    /// Windows Forms application, edited, deleted, and connected to members
    /// through the MemberMinistry model.
    /// </summary>
    public class Ministry
    {
        /// <summary>
        /// Gets or sets the unique identifier for the ministry.
        ///
        /// This value is generated by the database and is used to identify
        /// each ministry separately. It is also used for database operations
        /// such as finding, updating, deleting, or linking a ministry
        /// to members.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the name of the ministry.
        ///
        /// This property stores the name that identifies the ministry
        /// in the application, such as Music Ministry, Youth Ministry,
        /// Usher Ministry, or Prayer Ministry.
        ///
        /// The name is required so that every ministry has a clear identity.
        /// </summary>
        public required string Name { get; set; }

        /// <summary>
        /// Gets or sets the description of the ministry.
        ///
        /// This property stores information that explains the purpose,
        /// responsibilities, or activities of the ministry.
        ///
        /// The description can be displayed in the Ministry Management
        /// and Edit Ministry forms to help users understand the ministry.
        /// </summary>
        public required string Description { get; set; }
    }
}