using System;
using System.Collections.Generic;
using System.Security.Policy;
using System.Text;

namespace MemberCrud.Models;


/// <summary>
/// Represents a message sent by a volunteer to the church administration.
///
/// This class is used to store communication between a church volunteer
/// and the church administration. Each message includes the volunteer
/// who sent it, the message content, and the date and time it was sent.
///
/// VolunteerMessage objects can be saved to the database, displayed
/// in the application, and used to keep track of volunteer questions,
/// feedback, or requests.
/// </summary>
public class VolunteerMessage
{
    /// <summary>
    /// The unique identifier for the volunteer message.
    ///
    /// This value is automatically generated by the database and is
    /// used to identify each message.
    /// </summary>

    public int Id { get; set; }
    /// <summary>
    /// The unique identifier of the member who sent the message.
    ///
    /// This property links the message to a specific member in the
    /// Members table.
    /// </summary>
    public int MemberId { get; set; }

    /// <summary>
    /// The text of the message sent by the volunteer.
    ///
    /// This property stores the message that will be read by the
    /// church administration.
    /// </summary>

    public required string MessageText { get; set; }

    public DateTime SentAt { get; set; }
}
